# Generated by Django 5.1.1 on 2024-09-21 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('imdbID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('released', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('imdbRating', models.FloatField()),
                ('poster', models.CharField(max_length=255)),
                ('plot', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('imdbID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='infovanaDB.titulo')),
                ('runtime', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('imdbID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='infovanaDB.titulo')),
                ('totalSeasons', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('imdbID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='infovanaDB.titulo')),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('runtime', models.CharField(max_length=255)),
                ('imdbID_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infovanaDB.serie')),
            ],
        ),
        migrations.CreateModel(
            name='TituloxUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infovanaDB.titulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('imdbID', 'user'), name='unique_tituloxuser')],
            },
        ),
    ]
