# Generated by Django 5.1.1 on 2024-09-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infovanaDB', '0002_alter_titulo_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='imdbRating',
            field=models.CharField(max_length=10),
        ),
    ]
